name: Landscapes
favicon: null
layout_spectrum: 0.31338
typography_spectrum: 0.50001
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3125
  lightness: 0.543794468510896
  saturation: 0.6490870567504317
  rhythmicContrast: 0.03259901190176606
purpose: []
